baseurl = "https://www.akhaled.net/"
title = "Ahmed's corner"
theme = "hugo-theme-console"
languageCode = "en-us"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "github"
    tabWidth = 4

[params]
  animateStyle = "animated zoomIn fast"
  customCSS = ["css/custom.css"]

  [[params.navlinks]]
  name = "CV"
  url = "pdfs/cv.pdf"

  [[params.navlinks]]
  name = "Scholar"
  url = "https://scholar.google.com/citations?user=Bc3wOdsAAAAJ&hl=en"

  [[params.navlinks]]
  name = "GitHub"
  url = "https://github.com/rka97"

